name: myghaction

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Log repo name to console
              run: echo 'Repository name = $GITHUB_REPOSITORY'
              