name: myghaction

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Log repo name to console
              run: echo Repository name $GITHUB_REPOSITORY

            - uses: actions/checkout@v2
                
            - name: Push to Docker Hub
              uses: docker/build-push-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: ntrogh/wallofzen1
                  tags: latest,${{ github.sha }}
                  tag_with_ref: false

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: azure/login@v1.1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
  
            - uses: 'azure/aci-deploy@v1'
              id: aci-deploy
              with:
                  resource-group: devopsdaysams
                  dns-name-label: wallofzen3
                  image: ntrogh/wallofzen1:${{ github.sha }}
                  name: ntwallofzen3
                  location: 'west europe'
                  environment-variables: BASE_URL=https://devopsdaysams.azurewebsites.net/api/AddToWall

            - name: 'Output ACI url'
              run: echo "ACI URL is ${{ steps.aci-deploy.outputs.app-url }}"

            - name: 'Output API url'
              run: echo "API url is ${{ steps.aci-deploy.outputs.app-url }}addtowall?repoUrl=https://github.com/${{ github.repository }}"

            - name: Curl API
              run: |
                curl "${{ steps.aci-deploy.outputs.app-url }}addtowall?repoUrl=https://github.com/${{ github.repository }}"
    
